name: Deploy Pages

on:
  push:
    branches: [main]
    paths:
      - "data/**"
      - "index.html"
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Prepare site files
        run: |
          mkdir -p _site
          find . -type f ! -name "*.xlsx" ! -name "*.txt" ! -name "*.py" -exec cp --parents {} _site/ \;

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: "./_site"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
