name: Auto Update

on:
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  Update:
    runs-on: ubuntu-latest
    outputs:
      has_changes: ${{ steps.commit.outputs.has_changes }}

    steps:
      - name: Clone Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Set Timezone to UTC+8
        run: |
          sudo timedatectl set-timezone Asia/Taipei
          echo "Current time: $(date)"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14.x"
          cache: "pip"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Python
        run: python main.py

      - name: Commit Files
        id: commit
        run: |
          git config --global user.name 'Canaan-HS'
          git config --global user.email 's3459897@gmail.com'

          if [[ -n $(git status -s) ]]; then
            git add -A
            git commit -m "Update"
            git push
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "No changes"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi
