name: Auto Update

on:
  schedule:
    - cron: "0 4,10,16,22 * * *"
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  Update:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Set Timezone to UTC+8
        run: |
          sudo timedatectl set-timezone Asia/Taipei
          echo "Current time: $(date)"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14.x"
          cache: "pip"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Python
        run: python main.py

      - name: Commit and Push Files
        run: |
          git config --global user.name 'Canaan-HS'
          git config --global user.email 's3459897@gmail.com'

          if [[ -n $(git status -s) ]]; then
            echo "Changes detected. Committing and pushing..."
            git add -A
            git commit -m "Auto update"
            git push
          else
            echo "No changes to commit."
          fi
